services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-bulldoc-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      - NODE_DEBUG=request
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_CUSTOM_EXTENSIONS=/bulldoc-node
    ports:
      - 5678:5678
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./dist:/bulldoc-node/dist
